# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Philtre of Volubility
tagline:          'Learing Elixir by building a Slack client'
description:      'Learing Elixir by building a Slack client'
url:              http://speck.duien.com
baseurl:          /

author:
  name:           'Emily Hyland'
  url:            https://twitter.com/duien

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/duien/speck

emoji:
  src: /public/

gems:
  - jekyll-paginate
  - jemoji
